In [2]:
import polars as pl
from wequant.data_loading import read_data
from datetime import date

In [3]:
ori_df = read_data("../../data/datasets/ds-quarterly-valuation-operating-announcement-20260928_150853.parquet")
df = read_data("../../data/datasets/prepared/quarterly-valuation-20261010_114319.parquet")
pl.Config.set_tbl_rows(20)

polars.config.Config

In [10]:
df1 = ori_df.filter(pl.col("setd")==date(2026, 6, 30))

In [11]:
df1[:20]

shape: (0, 15)
┌──────┬──────┬──────┬──────┬───┬─────┬──────┬──────┬─────┐
│ code ┆ name ┆ setd ┆ annd ┆ … ┆ PER ┆ divr ┆ perf ┆ bm  │
│ ---  ┆ ---  ┆ ---  ┆ ---  ┆   ┆ --- ┆ ---  ┆ ---  ┆ --- │
│ i64  ┆ str  ┆ date ┆ date ┆   ┆ f64 ┆ f64  ┆ f64  ┆ f64 │
╞══════╪══════╪══════╪══════╪═══╪═════╪══════╪══════╪═════╡
└──────┴──────┴──────┴──────┴───┴─────┴──────┴──────┴─────┘

In [28]:
df.sort(by=["ngrpr"], descending=[True]).filter(pl.col("grsl").is_not_null())

shape: (217, 8)
┌──────┬────────────┬────────────┬─────┬────────────┬──────────────┬───────────┬────────────┐
│ code ┆ setd       ┆ annd       ┆ qtr ┆ grsl       ┆ ngrpr        ┆ PER       ┆ target     │
│ ---  ┆ ---        ┆ ---        ┆ --- ┆ ---        ┆ ---          ┆ ---       ┆ ---        │
│ i64  ┆ date       ┆ date       ┆ i64 ┆ f64        ┆ f64          ┆ f64       ┆ f64        │
╞══════╪════════════╪════════════╪═════╪════════════╪══════════════╪═══════════╪════════════╡
│ 1384 ┆ 2025-06-30 ┆ 2025-08-13 ┆ 1   ┆ 33.675331  ┆ 1054.695656  ┆ 10.21     ┆ -1.105906  │
│ 1718 ┆ 2025-03-31 ┆ 2025-04-28 ┆ 1   ┆ 18.821626  ┆ 713.788594   ┆ 6.17      ┆ 8.061058   │
│ 4317 ┆ 2025-05-31 ┆ 2025-07-14 ┆ 1   ┆ 38.544358  ┆ 682.710138   ┆ 8.98      ┆ 2.496692   │
│ 7800 ┆ 2024-12-31 ┆ 2025-02-14 ┆ 1   ┆ 10.493827  ┆ 672.067901   ┆ 13.57     ┆ -0.902092  │
│ 5729 ┆ 2025-06-30 ┆ 2025-08-01 ┆ 1   ┆ 121.895559 ┆ 569.243802   ┆ 8.09      ┆ -20.46331  │
│ 9083 ┆ 2024-06-30 ┆ 2024-08-06 ┆ 1   ┆ 11.07327   ┆ 552.797082   ┆ 11.55     ┆ 1.506995   │
│ 6748 ┆ 2025-03-31 ┆ 2025-05-13 ┆ 1   ┆ 15.204138  ┆ 516.349529   ┆ 5.91      ┆ 1.392209   │
│ 1418 ┆ 2024-05-31 ┆ 2024-07-12 ┆ 1   ┆ 42.231874  ┆ 447.260032   ┆ 12.257181 ┆ -4.290763  │
│ 6941 ┆ 2024-06-30 ┆ 2024-08-06 ┆ 1   ┆ 71.452875  ┆ 408.724084   ┆ 11.67     ┆ -0.209656  │
│ 1777 ┆ 2025-06-30 ┆ 2025-07-31 ┆ 1   ┆ 96.188001  ┆ 385.524542   ┆ 9.37      ┆ -28.033214 │
│ …    ┆ …          ┆ …          ┆ …   ┆ …          ┆ …            ┆ …         ┆ …          │
│ 9790 ┆ 2025-06-30 ┆ 2025-08-08 ┆ 1   ┆ 13.616777  ┆ 17.377103    ┆ 14.7      ┆ -2.372026  │
│ 9273 ┆ 2025-09-30 ┆ 2025-11-07 ┆ 1   ┆ 18.380744  ┆ 16.850842    ┆ 9.07      ┆ -3.51121   │
│ 4776 ┆ 2026-03-31 ┆ 2026-05-14 ┆ 1   ┆ 16.976824  ┆ 16.375019    ┆ 13.191158 ┆ -1.466719  │
│ 3817 ┆ 2024-06-30 ┆ 2024-08-07 ┆ 1   ┆ 10.475656  ┆ 14.561402    ┆ 10.78     ┆ -0.359227  │
│ 6858 ┆ 2025-03-31 ┆ 2025-04-24 ┆ 1   ┆ 23.247354  ┆ -28.783814   ┆ 10.03     ┆ 1.631255   │
│ 1967 ┆ 2024-06-30 ┆ 2024-08-05 ┆ 1   ┆ 12.742696  ┆ -69.387793   ┆ 9.11      ┆ -6.532845  │
│ 9537 ┆ 2025-06-30 ┆ 2025-08-08 ┆ 1   ┆ 12.312699  ┆ -108.197272  ┆ 8.79      ┆ 0.93639    │
│ 3392 ┆ 2025-06-30 ┆ 2025-08-07 ┆ 1   ┆ 11.377334  ┆ -675.09552   ┆ 10.38     ┆ 3.99456    │
│ 3280 ┆ 2025-05-31 ┆ 2025-07-11 ┆ 1   ┆ 166.016797 ┆ -1032.141444 ┆ 4.66      ┆ 1.267405   │
│ 1841 ┆ 2024-06-30 ┆ 2024-08-14 ┆ 1   ┆ 37.573563  ┆ -1207.156494 ┆ 11.78     ┆ -3.545603  │
└──────┴────────────┴────────────┴─────┴────────────┴──────────────┴───────────┴────────────┘

In [32]:
ori_df.sort(by=["dgrp"], descending=[True]).filter(pl.col("grsl").is_not_null()).filter(pl.col("dgrp").is_not_null())

shape: (71_659, 15)
┌──────┬─────────────┬────────────┬────────────┬───┬───────────┬──────────┬────────────┬───────────┐
│ code ┆ name        ┆ setd       ┆ annd       ┆ … ┆ PER       ┆ divr     ┆ perf       ┆ bm        │
│ ---  ┆ ---         ┆ ---        ┆ ---        ┆   ┆ ---       ┆ ---      ┆ ---        ┆ ---       │
│ i64  ┆ str         ┆ date       ┆ date       ┆   ┆ f64       ┆ f64      ┆ f64        ┆ f64       │
╞══════╪═════════════╪════════════╪════════════╪═══╪═══════════╪══════════╪════════════╪═══════════╡
│ 6302 ┆ 住友重機械  ┆ 2023-09-30 ┆ 2023-11-09 ┆ … ┆ null      ┆ null     ┆ 5.105105   ┆ 0.808477  │
│      ┆ 工業        ┆            ┆            ┆   ┆           ┆          ┆            ┆           │
│ 9787 ┆ イオンディ  ┆ 2023-02-28 ┆ 2023-04-11 ┆ … ┆ null      ┆ null     ┆ -1.655629  ┆ -0.47665  │
│      ┆ ライト      ┆            ┆            ┆   ┆           ┆          ┆            ┆           │
│ 4182 ┆ 三菱瓦斯化  ┆ 2020-03-31 ┆ 2020-05-12 ┆ … ┆ null      ┆ null     ┆ 6.081871   ┆ -0.169099 │
│      ┆ 学          ┆            ┆            ┆   ┆           ┆          ┆            ┆           │
│ 4023 ┆ クレハ      ┆ 2025-12-31 ┆ 2026-02-09 ┆ … ┆ 19.12     ┆ 4.79     ┆ 3.305785   ┆ -0.352451 │
│ 9433 ┆ KDDI        ┆ 2024-03-31 ┆ 2024-05-10 ┆ … ┆ null      ┆ null     ┆ -0.300996  ┆ -5.861522 │
│ 6292 ┆ カワタ      ┆ 2025-06-30 ┆ 2025-07-31 ┆ … ┆ 30.90004  ┆ 4.515577 ┆ -17.61427  ┆ 1.287047  │
│ 9532 ┆ 大阪瓦斯    ┆ 2025-06-30 ┆ 2025-07-31 ┆ … ┆ 11.906886 ┆ 2.753701 ┆ 8.463357   ┆ 0.945327  │
│ 9697 ┆ カプコン    ┆ 2024-03-31 ┆ 2024-05-09 ┆ … ┆ null      ┆ null     ┆ 3.057494   ┆ 0.268229  │
│ 5301 ┆ 東海カーボ  ┆ 2023-09-30 ┆ 2023-11-07 ┆ … ┆ null      ┆ null     ┆ -4.980469  ┆ 1.247033  │
│      ┆ ン          ┆            ┆            ┆   ┆           ┆          ┆            ┆           │
│ 7421 ┆ カッパ・ク  ┆ 2026-03-31 ┆ 2026-05-08 ┆ … ┆ 51.06     ┆ 0.0      ┆ -3.111111  ┆ 1.652224  │
│      ┆ リエイト    ┆            ┆            ┆   ┆           ┆          ┆            ┆           │
│ …    ┆ …           ┆ …          ┆ …          ┆ … ┆ …         ┆ …        ┆ …          ┆ …         │
│ 6492 ┆ 岡野バルブ  ┆ 2024-08-31 ┆ 2024-10-04 ┆ … ┆ 13.06     ┆ 0.75     ┆ -12.898551 ┆ -1.363331 │
│      ┆ 製造        ┆            ┆            ┆   ┆           ┆          ┆            ┆           │
│ 7931 ┆ 未来工業    ┆ 2021-03-31 ┆ 2021-04-27 ┆ … ┆ null      ┆ null     ┆ -0.243605  ┆ -0.848742 │
│ 6840 ┆ AKIBA HD    ┆ 2023-12-31 ┆ 2024-02-13 ┆ … ┆ null      ┆ null     ┆ 0.985222   ┆ 0.292995  │
│ 4404 ┆ ミヨシ油脂  ┆ 2024-12-31 ┆ 2025-02-10 ┆ … ┆ 6.25      ┆ 4.02     ┆ -3.721205  ┆ 1.199555  │
│ 1381 ┆ アクシーズ  ┆ 2022-06-30 ┆ 2022-08-12 ┆ … ┆ null      ┆ null     ┆ 0.0        ┆ 1.132581  │
│ 4934 ┆ プレミアア  ┆ 2022-01-31 ┆ 2022-03-14 ┆ … ┆ null      ┆ null     ┆ -21.265823 ┆ -2.973726 │
│      ┆ ンチエイジ  ┆            ┆            ┆   ┆           ┆          ┆            ┆           │
│      ┆ ング        ┆            ┆            ┆   ┆           ┆          ┆            ┆           │
│ 6810 ┆ マクセル    ┆ 2023-06-30 ┆ 2023-07-27 ┆ … ┆ null      ┆ null     ┆ 0.661853   ┆ 0.102728  │
│ 6370 ┆ 栗田工業    ┆ 2025-12-31 ┆ 2026-02-05 ┆ … ┆ 23.24     ┆ 1.46     ┆ 5.438402   ┆ -0.60825  │
│ 6937 ┆ 古河電池    ┆ 2021-12-31 ┆ 2022-02-03 ┆ … ┆ null      ┆ null     ┆ -6.592466  ┆ -0.100983 │
│ 3101 ┆ 東洋紡      ┆ 2023-03-31 ┆ 2023-05-11 ┆ … ┆ null      ┆ null     ┆ -3.778097  ┆ 1.595486  │
└──────┴─────────────┴────────────┴────────────┴───┴───────────┴──────────┴────────────┴───────────┘