In [1]:
from datetime import date

#####
##### パラメータの設定
##### 
code = 2393
valuation_date = date.today()

In [2]:
#####
##### import objects
#####
from pathlib import Path
import os, sys

CURRENT_DIR = Path(os.getcwd())
PJ_DIR = CURRENT_DIR.parent.parent
LIB_DIR = PJ_DIR / "lib"
DATA_DIR = PJ_DIR / "data" 

sys.path.append(str(LIB_DIR))

from lib_dataprocess import KessanPl,  KessanFig, FinancequotePl, ShikihoOnlinePl, PricelistFig, PricelistPl
import polars as pl
from datetime import timedelta

In [3]:
#####
##### １．年度毎過去業績の棒＆折線グラフ
#####
KFIG = KessanFig(code, "通期", end_settlement_date=valuation_date)
KFIG.add_trace_profits()
KFIG.fig.show()

In [4]:
#####
##### ２．今年度予想業績＆前年度業績表
#####
KPL = KessanPl()
KPL.get_next_and_last_yearly_settlement(code, valuation_date)

shape: (2, 11)
┌──────┬─────────────┬─────────────┬─────────────┬───┬────────────┬────────────┬──────────┬────────┐
│ code ┆ settlement_ ┆ settlement_ ┆ announcemen ┆ … ┆ final_prof ┆ reviced_ep ┆ dividend ┆ quater │
│ ---  ┆ date        ┆ type        ┆ t_date      ┆   ┆ it         ┆ s          ┆ ---      ┆ ---    │
│ i64  ┆ ---         ┆ ---         ┆ ---         ┆   ┆ ---        ┆ ---        ┆ f64      ┆ i64    │
│      ┆ date        ┆ str         ┆ date        ┆   ┆ i64        ┆ f64        ┆          ┆        │
╞══════╪═════════════╪═════════════╪═════════════╪═══╪════════════╪════════════╪══════════╪════════╡
│ 2393 ┆ 2026-03-31  ┆ 予          ┆ 2026-01-30  ┆ … ┆ 2200       ┆ 141.6      ┆ 72.0     ┆ 4      │
│ 2393 ┆ 2025-03-31  ┆ 本          ┆ 2025-05-08  ┆ … ┆ 1792       ┆ 115.4      ┆ 70.0     ┆ 4      │
└──────┴─────────────┴─────────────┴─────────────┴───┴────────────┴────────────┴──────────┴────────┘

In [5]:
#####
##### ３．年度毎過去業績の棒＆折線グラフ
#####
KFIG = KessanFig(code, "四半期", end_settlement_date=valuation_date)
KFIG.add_trace_profits()
KFIG.fig.show()

In [6]:
#####
##### ４．四半期業績推移表
#####
limit = 8
KPL.get_quater_settlement_history(code, valuation_date, limit)

shape: (8, 11)
┌──────┬─────────────┬─────────────┬─────────────┬───┬────────────┬────────────┬──────────┬────────┐
│ code ┆ settlement_ ┆ settlement_ ┆ announcemen ┆ … ┆ final_prof ┆ reviced_ep ┆ dividend ┆ quater │
│ ---  ┆ date        ┆ type        ┆ t_date      ┆   ┆ it         ┆ s          ┆ ---      ┆ ---    │
│ i64  ┆ ---         ┆ ---         ┆ ---         ┆   ┆ ---        ┆ ---        ┆ f64      ┆ i64    │
│      ┆ date        ┆ str         ┆ date        ┆   ┆ i64        ┆ f64        ┆          ┆        │
╞══════╪═════════════╪═════════════╪═════════════╪═══╪════════════╪════════════╪══════════╪════════╡
│ 2393 ┆ 2025-12-31  ┆ 四          ┆ 2026-01-30  ┆ … ┆ 574        ┆ 37.0       ┆ 9.6      ┆ 3      │
│ 2393 ┆ 2025-09-30  ┆ 四          ┆ 2025-10-29  ┆ … ┆ 582        ┆ 37.5       ┆ 10.0     ┆ 2      │
│ 2393 ┆ 2025-06-30  ┆ 四          ┆ 2025-07-30  ┆ … ┆ 464        ┆ 29.9       ┆ 8.1      ┆ 1      │
│ 2393 ┆ 2025-03-31  ┆ 四          ┆ 2025-05-08  ┆ … ┆ 545        ┆ 35.1       ┆ 7.5      ┆ 4      │
│ 2393 ┆ 2024-12-31  ┆ 四          ┆ 2025-01-31  ┆ … ┆ 471        ┆ 30.3       ┆ 8.5      ┆ 3      │
│ 2393 ┆ 2024-09-30  ┆ 四          ┆ 2024-10-29  ┆ … ┆ 429        ┆ 27.6       ┆ 8.1      ┆ 2      │
│ 2393 ┆ 2024-06-30  ┆ 四          ┆ 2024-07-30  ┆ … ┆ 347        ┆ 22.4       ┆ 6.6      ┆ 1      │
│ 2393 ┆ 2024-03-31  ┆ 四          ┆ 2024-05-08  ┆ … ┆ 514        ┆ 33.1       ┆ 7.9      ┆ 4      │
└──────┴─────────────┴─────────────┴─────────────┴───┴────────────┴────────────┴──────────┴────────┘

In [7]:
#####
##### ５．評価日におけるファンダメンタル
#####

FPL = FinancequotePl()
FPL.print_finance_info(code, valuation_date=valuation_date)

日本ケアサプライ(2393)の銘柄情報

終値: 2392.0円(2026年01月23日)
予想配当利回り: 2.96%(2026年02月20日)
予想PER: 17.16倍(2026年02月20日)
実績PBR: 2.1倍(2026年02月20日)
自己資本比率: 65.5%(2026年02月20日)
予想ROE: 決算予想がないため、表示不可
予想ROA: 決算予想がないため、表示不可
時価総額: -億円(2026年02月20日)

In [8]:
#####
##### ６．評価日における四季報
#####
SOPL = ShikihoOnlinePl()
SOPL.print_latest_stock_df(
    code = code,
    target_date = valuation_date
)

2393(日本ケアサプライ)の2025年12月17日発行四季報データ
【最高益更新】
  主力の福祉用具レンタルは都市部を軸に拡大続く。病院・介護事業者向けの冷凍弁当も順調。レンタル資材の運用効率化が想定超。下期発生の資材償却費や人件費を吸収して営業益やや増額。27年3月期は福祉用具レンタルの伸びが続く。
【冷凍弁当】
  由美かおる氏とアンバサダー契約、冷凍弁当の認知拡大を狙う。女性の営業担当者を増やすための研修を実施。

In [9]:
######
###### ６．チャート
######
Pl_fig = PricelistFig(
    code,
    start_date = valuation_date - timedelta(days=365)
)
Pl_fig.add_vline_announcement_date()
Pl_fig.fig.show()

In [10]:
# memo 25/10
# オーテック：　空調建設関連　1Q好調、4半期偏重
# 不動テトラ：　陸上、海洋土木。受注好調。国土強靭化銘柄でもある？　季節偏重ありも、固そう。
# 3449(テクノフレックス)：　半導体好調。米国も好調。真空管。固そう。
# 1967　ヤマト：　関東地盤の空調・衛生など管工事。水道工事も。配管の生産システムに強み。

In [11]:
# 2026/1/18
### 石油資源開発は、売りか。
### コムシスはDC需要期待していたが、期待ほどでもないので、売りか
# 日東紡績は、低perに見えるが、株売却特別益の下駄のおかげ。業績は絶好調だが、27/3の会社計画を元にすると、perは30倍前後。値上げ浸透期待
# セルシスは、バグでよくわからない
# Shiftは業績予想不明につき、別途確認。株価の下げ激しい。per20倍前後。売上高成長も、1Q単体は減益。踊り場？少し様子見。
# KHネオケムは今期の業績が予想に対して芳しくない。高配当なので、継続保有するが。。。
## アクリートは予想発表なし。20倍台後半。成長を見込んでの保有なので、今後業績の成長が継続するかどうかがカギ。次の決算までは保有。
# 大塚HDは会社業績予想なし。25/12月期はまぁまぁ成長継続。配当利回り1.55%、予想per15倍前後(四季報)。26/12は減収減益を予想した数字。
### ENEOSは、減収減益基調も、株価は好調。perもそれなりに高くなっており、売り時か。
# 住友ゴムは株価好調。業績は横ばい。per15倍前後、配当利回り2%半ば。何が期待されているのか。。。
# 日本ヒュームは、高くなりすぎてるが、すでに元本回収済なので、国策にのって、様子見per25倍超、配当利回り1%強。
# ジャパンエンジンper30, 配当利回り0.5も、1, 2Qの業績は順調、会社計画保守的か。国策。もう少しもっとく感じか。
# 豊和工業は、業績がよめない。特需に備えての先行投資で減益？1Q, 2Q売上高は好調で会社予想と乖離あり。国策ならこれから業績上向きか。
# 野村マイクロは大口案件の動向で売上、利益ともに変動激しい。ただし、ファブレスで利益率は安定。受注好調につき、今後の大型案件獲得に期待ではあるが。。。
# 月島HDは上下水道関連。低per8.8倍, 2.63%配当性向。直近2Q好調。4Q偏重
# ダイキンはper20倍前後、配当利回り1.65%。長期成長期待。
# 栗田工業はper22, 配当利回り1.5%程度。直近はしぶく成長。この半年、株価は好調。水処理大手。長期成長期待。
## PILLARは、減収減益傾向ながら、per19.57倍、配当1.73%。生成AI期待。
# 三桜工業は、配当3.08%/PER18.06倍、減収減益傾向。DC向け空冷装置で電力コスト・環境負荷低減に貢献する『アクティブフラップドア』を開発。DC特需期待。
# 日本電子材料は、電子基盤検査用プローブカード主力。PER17.06倍配当1.39%。上期好調。成長率も高い。
# 日本アビオニクスは、配当0.18%PER31.61倍、直近2Qは大きく増収増益。防衛向け情報システム受注が想定以上に拡大。EV向け接合機器も日・中で好調とのこと。20%成長、売上高200億ちょいから26/3250億予想
# 三井ESは、予想PER: 26.9倍、予想配当利回りは0.5%程度？　港湾クレーンや船舶エンジンなど、防衛、グリーン関連。受注好調とのことで、数四半期は保有しつつ様子見
# ジェイリースは、配当3.38%、予想PER: 11.57倍。上期実績大幅増収増益、予想も大幅増収増益、長期保有。
# アイドマは1.33%,PER: 14.61倍、大幅増収増益。株価は直近決算発表日にストップ安。あまりスケールしないビジネスかも。業績成長が継続する限り、現状で保有か。
# 東京計器は、0.55%、PER: 42.11倍。防衛関連で上昇し、高い。4Q偏重で予想たてづらい。実績がでるのはこれからだが。。。
# 東京精密は、1.74%、予想PER: 25.3倍。上期増収増益。精密技術優位。HBM向けに主力？これから期待。
# フルヤ金属は、1.86%、PER: 16.49倍。直近1Qは大幅増収。やや増益。旺盛なデータセンター投資でHDD向けターゲット伸長とのこと。高利益率。長期保有。
# 伊藤忠商事は、1.98%、予想PER: 16.61倍。perはまぁまぁ。
# 丸紅は、1.92%、予想PER: 16.82倍。かつては高配当銘柄だったけど、、、。
# ユニ・チャームは、2.0%、予想PER: 18.51倍。中期的にだいぶ下げた。ブランドプレミアムを考えると手頃か。株価は長期低迷中。